import Head from 'next/head'
import PayoutsScreen from '../screens/payouts'
import style from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Payouts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.container}>
        <PayoutsScreen/>
      </main>
    </div>
    
  )
}
